apiVersion: apps/v1
kind: Deployment
metadata:
  name: container2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container2
  template:
    metadata:
      labels:
        app: container2
    spec:
      containers:
      - name: container2
        image: us-central1-docker.pkg.dev/container-app/container-repo/container2
        ports:
        - containerPort: 6001
        volumeMounts:
        - name: data-volume
          mountPath: /data
      volumes:
      - name: data-volume
        hostPath:
          path: /data
---
apiVersion: v1
kind: Service
metadata:
  name: container2-service
spec:
  selector:
    app: container2
  ports:
    - protocol: TCP
      port: 6001
      targetPort: 6001
  type: ClusterIP
